Repository munich-quantum-toolkit/qecc, pull requests merged in 2023-03, with the labels that each got.

#89 ✨ Add LightsOut Decoder
  .flake8
  .github/codecov.yml
  .pre-commit-config.yaml
  README.md
  docs/source/EccFramework.rst
  docs/source/Installation.rst
  docs/source/LightsOutDecoder.ipynb
  docs/source/conf.py
  docs/source/images/cc.png
  docs/source/images/lights-out.png
  docs/source/images/lo.png
  docs/source/images/steane-ex.png
  docs/source/index.rst
  docs/source/library/Library.rst
  docs/source/library/LightsOutDecoder.rst
  mqt/qecc/cc_decoder/__init__.py
  mqt/qecc/cc_decoder/cli.py
  mqt/qecc/cc_decoder/comparison/tn_decoder.py
  mqt/qecc/cc_decoder/decoder.py
  mqt/qecc/cc_decoder/hexagonal_color_code.py
  mqt/qecc/cc_decoder/plots.py
  mqt/qecc/cc_decoder/run.sh
  pyproject.toml
  test/python/test_cc_decoder.py
Labels: enhancement

#100 📝 Add arXiv link to documentation
  README.md
  docs/source/Publications.rst
  docs/source/refs.bib
Labels: documentation

#103 🩹 Fix deprecation warnings related to qiskit-aer
  mqt/qecc/ecc_qiskit_wrapper.py
  pyproject.toml
  test/python/test_ecc_framework.py
Labels: bug, dependencies
