Repository munich-quantum-toolkit/qecc, pull requests merged in 2024-08, with the labels that each got.

#250 Bye flint
  .github/workflows/reusable-code-ql.yml
  .github/workflows/reusable-cpp-ci.yml
  .github/workflows/reusable-cpp-linter.yml
  .github/workflows/reusable-python-ci.yml
  .github/workflows/reusable-python-packaging.yml
  .readthedocs.yaml
  CMakeLists.txt
  cmake/ExternalDependencies.cmake
  cmake/FindFLINT.cmake
  cmake/FindGMP.cmake
  cmake/FindMPFR.cmake
  docs/source/Installation.rst
  include/Code.hpp
  include/Utils.hpp
  pyproject.toml
  src/CMakeLists.txt
  src/DecodingSimulator.cpp
  src/UFDecoder.cpp
  src/Utils.cpp
  test/app.cpp
  test/test_originalUfd.cpp
  test/test_utils.cpp
Labels: enhancement, dependencies, minor

#256 🚚 transfer the ECC framework code from MQT Core
  include/ecc/Ecc.hpp
  include/ecc/Id.hpp
  include/ecc/Q18Surface.hpp
  include/ecc/Q3Shor.hpp
  include/ecc/Q5Laflamme.hpp
  include/ecc/Q7Steane.hpp
  include/ecc/Q9Shor.hpp
  include/ecc/Q9Surface.hpp
  src/CMakeLists.txt
  src/ecc/CMakeLists.txt
  src/ecc/Ecc.cpp
  src/ecc/Q18Surface.cpp
  src/ecc/Q3Shor.cpp
  src/ecc/Q5Laflamme.cpp
  src/ecc/Q7Steane.cpp
  src/ecc/Q9Shor.cpp
  src/ecc/Q9Surface.cpp
  src/python/CMakeLists.txt
  src/python/bindings.cpp
  test/CMakeLists.txt
  test/test_ecc_functionality.cpp
Labels: usability, refactor

#267 Fix small code bugs for FT Stateprep
  src/mqt/qecc/ft_stateprep/state_prep.py
  test/python/ft_stateprep/test_stateprep.py
Labels: fix

#268 Fix circuit errors
  src/mqt/qecc/ft_stateprep/eval/circuits/carbon/zero_non_ft_heuristic.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/carbon/zero_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_ft_heuristic_heuristic.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_ft_heuristic_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_ft_heuristic_opt.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_ft_heuristic_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_ft_opt_opt.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_ft_opt_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_non_ft_heuristic.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/plus_non_ft_heuristic.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/plus_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/zero_non_ft_heuristic.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/zero_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/shor/zero_non_ft_heuristic.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/shor/zero_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/plus_non_ft_heuristic.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/plus_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/zero_non_ft_heuristic.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/zero_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/tetrahedral/zero_non_ft_heuristic.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/tetrahedral/zero_non_ft_heuristic.stim
Labels: bug

#270 ✨ Infrastructure Update without Windows Support
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/reusable-python-ci.yml
  .github/workflows/reusable-python-packaging.yml
  .github/workflows/update-mqt-core.yml
  .pre-commit-config.yaml
  CMakeLists.txt
  README.md
  cmake/ExternalDependencies.cmake
  include/DecodingSimulator.hpp
  include/ecc/Ecc.hpp
  include/ecc/Id.hpp
  include/ecc/Q18Surface.hpp
  include/ecc/Q3Shor.hpp
  include/ecc/Q5Laflamme.hpp
  include/ecc/Q7Steane.hpp
  include/ecc/Q9Shor.hpp
  include/ecc/Q9Surface.hpp
  noxfile.py
  pyproject.toml
  src/DecodingSimulator.cpp
  src/Utils.cpp
  src/ecc/CMakeLists.txt
  src/ecc/Ecc.cpp
  src/ecc/Q18Surface.cpp
  src/ecc/Q3Shor.cpp
  src/ecc/Q5Laflamme.cpp
  src/ecc/Q7Steane.cpp
  src/ecc/Q9Shor.cpp
  src/ecc/Q9Surface.cpp
  src/mqt/qecc/analog_information_decoding/simulators/analog_tannergraph_decoding.py
  src/mqt/qecc/analog_information_decoding/simulators/memory_experiment_v2.py
  src/mqt/qecc/analog_information_decoding/simulators/simulation.py
  src/mqt/qecc/cc_decoder/decoder.py
  src/mqt/qecc/codes/css_code.py
  src/mqt/qecc/ecc_qiskit_wrapper.py
  src/mqt/qecc/ft_stateprep/simulation.py
  src/mqt/qecc/ft_stateprep/state_prep.py
  src/python/bindings.cpp
  test/python/ft_stateprep/test_simulation.py
  test/python/ft_stateprep/test_stateprep.py
  test/test_ecc_functionality.cpp
  test/test_originalUfd.cpp
Labels: enhancement, dependencies, github_actions, continuous integration, packaging, python, code quality

#272 Fix incorrect placement of z-errors
  src/mqt/qecc/ft_stateprep/state_prep.py
Labels: bug

#271 bye ldpc
  .github/workflows/ci.yml
  .github/workflows/reusable-code-ql.yml
  .github/workflows/reusable-cpp-linter.yml
  .pre-commit-config.yaml
  README.md
  cmake/ExternalDependencies.cmake
  include/Code.hpp
  include/Codes.hpp
  include/Decoder.hpp
  include/DecodingRunInformation.hpp
  include/GF2.hpp
  include/QeccException.hpp
  include/TreeNode.hpp
  include/UFDecoder.hpp
  include/UFHeuristic.hpp
  include/Utils.hpp
  pyproject.toml
  src/CMakeLists.txt
  src/GF2.cpp
  src/UFDecoder.cpp
  src/UFHeuristic.cpp
  src/Utils.cpp
  test/app.cpp
  test/test_originalUfd.cpp
  test/test_simulator.cpp
  test/test_treenode.cpp
  test/test_ufdheuristic.cpp
  test/test_utils.cpp
Labels: enhancement, dependencies, refactor
