Repository munich-quantum-toolkit/qecc, pull requests merged in 2024-11, with the labels that each got.

#317 📌 temporary `ldpc<2`
  pyproject.toml
Labels: dependencies, python, fix

#324 📝 Fixed wrong links in documentation
  docs/StatePrep.ipynb
Labels: documentation

#288 Extend functionality for working with codes.
  src/mqt/qecc/codes/__init__.py
  src/mqt/qecc/codes/concatenation.py
  src/mqt/qecc/codes/constructions.py
  src/mqt/qecc/codes/css_code.py
  src/mqt/qecc/codes/hamming_15/hx.npy
  src/mqt/qecc/codes/hamming_15/hz.npy
  src/mqt/qecc/codes/pauli.py
  src/mqt/qecc/codes/stabilizer_code.py
  src/mqt/qecc/codes/symplectic.py
  test/python/test_code.py
Labels: enhancement, feature, code quality

#334 Fixed documentation typo regarding the number of CNOT gates for the steane code
  docs/StatePrep.ipynb
Labels: documentation
