Repository munich-quantum-toolkit/qecc, pull requests merged in 2024-10, with the labels that each got.

#291 🔒 uv lock file
  .readthedocs.yaml
  docs/AnalogInfo.rst
  docs/Contributing.rst
  docs/DevelopmentGuide.rst
  docs/EccFramework.rst
  docs/Installation.rst
  docs/LightsOutDecoder.ipynb
  docs/Publications.rst
  docs/StatePrep.ipynb
  docs/Support.rst
  docs/_static/custom.css
  docs/_static/mqt_dark.png
  docs/_static/mqt_light.png
  docs/conf.py
  docs/full_ft_scheme.svg
  docs/images/488_color_code.svg
  docs/images/cc.png
  docs/images/lights-out.png
  docs/images/lo.png
  docs/images/steane-ex.png
  docs/index.rst
  docs/library/Code.rst
  docs/library/Decoder.rst
  docs/library/DecodingResult.rst
  docs/library/DecodingResultStatus.rst
  docs/library/DecodingRunInformation.rst
  docs/library/EccFramework.rst
  docs/library/GrowthVariant.rst
  docs/library/Library.rst
  docs/library/LightsOutDecoder.rst
  docs/library/SamplePauliError.rst
  docs/library/StatePrep.rst
  docs/library/UFDecoder.rst
  docs/library/UFHeuristic.rst
  docs/refs.bib
  docs/source/Contributing.rst
  docs/source/Support.rst
  docs/templates/page.html
  noxfile.py
  pyproject.toml
  uv.lock
Labels: dependencies, usability, python

#281 📝 Documentation updates
  README.md
  docs/DevelopmentGuide.rst
  docs/Installation.rst
Labels: documentation

#295 ⚗️ upload to Test PyPI for pushes on `main`
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/update-mqt-core.yml
  pyproject.toml
Labels: github_actions, continuous integration, packaging

#297 🔧 small project configuration updates
  .github/release-drafter.yml
  .github/renovate.json5
  .readthedocs.yaml
  noxfile.py
  pyproject.toml
Labels: code quality

#285 Adjustments to handling of hook errors in FT state preparation circuit synthesis
  src/mqt/qecc/ft_stateprep/eval/circuits/carbon/zero_ft_heuristic_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/carbon/zero_ft_heuristic_opt.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/carbon/zero_ft_heuristic_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/carbon/zero_ft_opt_opt.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/carbon/zero_ft_opt_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/carbon/zero_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/carbon/zero_non_ft_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/cc_4_8_8/zero_ft_heuristic_opt.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/cc_4_8_8/zero_ft_heuristic_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/cc_4_8_8/zero_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/cc_6_6_6/zero_ft_heuristic_opt.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/cc_6_6_6/zero_ft_heuristic_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/cc_6_6_6/zero_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_ft_heuristic_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_ft_heuristic_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_ft_opt_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/plus_non_ft_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/zero_ft_heuristic_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/zero_ft_heuristic_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/zero_ft_opt_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/zero_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/hamming/zero_non_ft_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/plus_ft_heuristic_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/plus_ft_heuristic_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/plus_ft_opt_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/plus_non_ft_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/zero_ft_heuristic_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/zero_ft_heuristic_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/zero_ft_opt_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d3/zero_non_ft_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/rotated_surface_d5/zero_ft_heuristic_opt.qasm
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/plus_ft_heuristic_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/plus_ft_heuristic_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/plus_ft_opt_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/plus_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/plus_non_ft_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/zero_ft_heuristic_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/zero_ft_heuristic_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/zero_ft_opt_opt.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/zero_non_ft_heuristic.stim
  src/mqt/qecc/ft_stateprep/eval/circuits/steane/zero_non_ft_opt.stim
  src/mqt/qecc/ft_stateprep/state_prep.py
  test/python/ft_stateprep/test_stateprep.py
Labels: enhancement, feature, fix
