Repository munich-quantum-toolkit/qecc, pull requests merged in 2024-09, with the labels that each got.

#277 ⬆️ update ldpc with numpy 2 and Python 3.12+ support
  .github/workflows/reusable-python-packaging.yml
  noxfile.py
  pyproject.toml
Labels: dependencies, python, fix

#266 🏁 Windows Support
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/reusable-cpp-ci.yml
  .github/workflows/reusable-python-ci.yml
  .github/workflows/reusable-python-packaging.yml
  .pre-commit-config.yaml
  CMakeLists.txt
  cmake/ExternalDependencies.cmake
  docs/source/conf.py
  include/Code.hpp
  include/UFDecoder.hpp
  noxfile.py
  pyproject.toml
  scripts/examples/atd_example.py
  scripts/examples/decoding-performance-simulations.py
  scripts/examples/runtime-simulations.py
  scripts/numerics/visualize/visualizeDecodingRuntime.py
  scripts/numerics/visualize/visualizeWordErrRate.py
  src/UFDecoder.cpp
  src/mqt/qecc/analog_information_decoding/code_construction/code_constructor.py
  src/mqt/qecc/analog_information_decoding/code_construction/sparse_code_constructor.py
  src/mqt/qecc/analog_information_decoding/simulators/memory_experiment_v2.py
  src/mqt/qecc/analog_information_decoding/simulators/quasi_single_shot_v2.py
  src/mqt/qecc/analog_information_decoding/simulators/simulation.py
  src/mqt/qecc/analog_information_decoding/utils/data_utils.py
  src/mqt/qecc/cc_decoder/decoder.py
  src/mqt/qecc/cc_decoder/plots.py
  test/python/analog_info/test_memory_experiment.py
  test/python/ft_stateprep/test_simulation.py
  test/python/ft_stateprep/test_stateprep.py
Labels: enhancement, continuous integration, usability, minor

#283 Fix error propagation.
  src/mqt/qecc/ft_stateprep/state_prep.py
Labels: bug
