Repository munich-quantum-toolkit/qecc, pull requests merged in 2025-06, with the labels that each got.

#426 Ignore qsample warnings.
  pyproject.toml
Labels: fix

#428 🎨 Fix pre-commit failure
  sitecustomize.py
Labels: code quality

#429 📝🩹 Disable PDF build on RtD
  .readthedocs.yaml
Labels: documentation, fix
