Repository munich-quantum-toolkit/qecc, pull requests merged in 2025-07, with the labels that each got.

#378 FT Cat State Prep
  docs/CatStates.md
  docs/index.md
  scripts/cat_states/estimate_error_rate.py
  scripts/cat_states/run_parallel.sh
  src/mqt/qecc/circuit_synthesis/__init__.py
  src/mqt/qecc/circuit_synthesis/cat_states.py
  src/mqt/qecc/circuit_synthesis/circuit_utils.py
  src/mqt/qecc/circuit_synthesis/noise.py
  test/python/circuit_synthesis/test_cat_states.py
  test/python/circuit_synthesis/test_utils.py
Labels: feature, minor

#442 🚸 Add changelog and upgrade guide
  CHANGELOG.md
  UPGRADING.md
  docs/CHANGELOG.md
  docs/UPGRADING.md
  docs/index.md
Labels: documentation

#440 👷 Enable templating
  .github/workflows/templating.yml
Labels: continuous integration

#458 Fix flaky test fails due to timeouts on macos.
  test/python/circuit_synthesis/test_cat_states.py
  test/python/circuit_synthesis/test_encoder_synthesis.py
  test/python/circuit_synthesis/test_stateprep.py
Labels: bug, continuous integration

#453 Add functionality to add noise to a Circuit.
  CHANGELOG.md
  src/mqt/qecc/circuit_synthesis/cat_states.py
  src/mqt/qecc/circuit_synthesis/circuit_utils.py
  src/mqt/qecc/circuit_synthesis/noise.py
  test/python/circuit_synthesis/test_noise.py
  test/python/circuit_synthesis/test_utils.py
Labels: feature

#456 Fix minor typo
  docs/CatStates.md
  src/mqt/qecc/analog_information_decoding/simulators/quasi_single_shot_v2.py
  src/mqt/qecc/cc_decoder/stim_interface/max_sat_sinter_decoder.py
  src/mqt/qecc/circuit_synthesis/state_prep.py
Labels: documentation
